version: "3"
 
services:
  mysql:
    image: mysql:5.7
    container_name: deepx-sql
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dev
      
  api:
    build: ./api/
    container_name: deepx-api
    environment:
      RAILS_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./api/:/app
    links:
      - "mysql"
    depends_on:
      - "mysql"

  nuxt:
    build: ./frontend/
    container_name: deepx-frontend
    restart: always
    ports:
      - "4000:3000"
    volumes:
      - ./frontend/:/frontend
    command:
      "npm run dev"