version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: deepx-sql
    ports:
      - "3306:3306"
    volumes:
      - ./api/tmp/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dev

  api:
    build: ./api/
    container_name: deepx-api
    environment:
      RAILS_ENV: development
    # command:
    #   ""
    ports:
      - "3000:3000"
    volumes:
      - ./api/:/app
    links:
      - "mysql"

  nuxt:
    build: ./frontend/
    container_name: deepx-frontend
    restart: always
    ports:
      - "8000:3000"
    volumes:
      - ./frontend/:/app
    command:
      "npm run start"

# mysql:
#   image: mysql:5.7
#   ports:
#     - "3306:3306"
#   volumes_from:
#     - dbdata
#   environment:
#     - MYSQL_ROOT_PASSWORD=root
#     - MYSQL_DATABASE=dev

# dbdata:
#   image: tianon/true
#   volumes:
#     - ./tmp/db:/var/lib/mysql

# api:
#   build: ./api/
#   environment:
#     RAILS_ENV: development
#   ports:
#     - '3000:3000'
#   volumes:
#     - .:/app
#   command:
#     "rails s -b 0.0.0.0"
#   links:
#     - "mysql"

# nuxt:
#   build: ./frontend/
#   restart: always
#   ports: 
#     - "3003:3003"
#   volumes:
#     - .:/app
#   command:
#     "npm run start"

# appdata:
#   image: tianon/true
#   volumes:
#     - ".:/workspace"
