rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - ruby-head
  - jruby-9.1.17.0
  - jruby-9.2.0.0

matrix:
  allow_failures:
    - rvm: jruby-9.1.17.0
    - rvm: jruby-9.2.0.0

before_script:
  - unset JRUBY_OPTS

script: rake

addons:
  apt:
    packages:
      - haveged
