version: '3'

volumes:
  store:
    driver: local
  bundle:
    driver: local

services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    links:
      - db
    stdin_open: true
    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    # environment: &app_env
    #   PORT: 3000
    #   DB_HOST: db
    #   DB_PORT: 3306
    #   DB_USER: root
    #   DB_PSWD:  
  db:
    image: memsql/quickstart
    ports:
      - 3306:3306
      - 8080:8080
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    # environment:
    #   POSTGRES_USER: root
    #   POSTGRES_PASSWORD: 
