mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  volumes_from:
    - dbdata
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=dev

dbdata:
  image: tianon/true
  volumes:
    - ./tmp/db:/var/lib/mysql

app:
  build: .
  environment:
    RAILS_ENV: development
  ports:
    - '3002:3000'
  volumes:
    - .:/app
  links:
    - "mysql"

# nuxt:
#   build: ../frontend/
#   restart: always
#   ports: 
#     - "3003:3003"
#   volumes:
#     - .:/app
#   command:
#     "npm run start"

# appdata:
#   image: tianon/true
#   volumes:
#     - ".:/workspace"
